# Site settings
title: "Diario de robótica de Jorge Lozoya Astudillo"
description: "Bitácora de prácticas de robótica en Unibotics."
url: "https://lozoyass.github.io" 
baseurl: ""

# Configuración del Tema
# Importante: Algunos entornos de GitHub necesitan 'theme' y otros 'remote_theme'. Ponemos ambos para asegurar.
theme: jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # Puedes probar "air", "aqua" o "contrast" si quieres cambiar colores

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins (Asegúrate de tener estos dos primeros siempre)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache